### ISSUE TITLE
YAML generation not well formed with "path" parameters

### ISSUE THREAD

**Issue by lfoppiano** [greyli/apiflask#209]
Basically I have two methods like this: 

```
@bp.route('/record/<id>/flag', methods=['PUT', 'PATCH'])
@output(Flag)
def flag_record(id):
   [...]
   
@bp.route('/record/<id>/unflag', methods=['PUT', 'PATCH'])
@output(Flag)
def unflag_record(id):
```

The output is something like: 

```yaml

  /supercon/record/{id}/flag:
    patch:
      parameters:
      - &id001
        in: path
        name: id
        required: true
        schema:
          type: string

[...]

/supercon/record/{id}/unflag:
    patch:
      parameters:
      - &id002
        in: path
        name: id
        required: true
        schema:
          type: string
```

The Open API validator fails with the following error: 
```
-attribute paths.'/record/{id}/unflag'. Declared path parameter id needs to be defined as a path parameter in path or operation level
-attribute paths.'/record/{id}/flag'. Declared path parameter id needs to be defined as a path parameter in path or operation level
```

You can see there are `&id001` and `&id002` that they are breaking the format. They are not there with the JSON  export. 

Environment:

- Python version: 3.8.12
- Flask version:  2.0.2
- APIFlask version: 0.11.0
